apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: enroller
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: registry.zouzland.com/enroller:0.0.13
          name: enroller
          env:
            - name: model_dir
              value: /opt/enroller
            - name: K_SINK
              value: http://data-controller.default
      imagePullSecrets:
        - name: regcred